name: "Fabrication - Panel"
on:
  push:
    paths:
      - '**/kibot-panel.yaml'
  workflow_dispatch:
  workflow_call:

jobs:
  fabrication-panel:
    uses: gcormier/kicad-jobs/.github/workflows/kicad-fabrication-panel.yaml@main
    permissions:
      contents: write